function (add_kernel_image NAME)
    if   (NOT KLEVER_TOOLS_BUSYBOX)
        message("[Klever] KLEVER_TOOLS_BUSYBOX must be enabled with enable_busybox()")
        message(SEND_ERROR)
    endif()

    string(APPEND PATH_BUSYBOX "${KLEVER_PATH_TOOLS}/busybox")
    string(APPEND PATH         "${KLEVER_PATH_IMAGE}/")
    string(APPEND PATH         "${NAME}/")
    string(APPEND PATH         "image")
    if    (EXISTS ${KLEVER_PATH_IMAGE}/${NAME}/${NAME}.img)
        return()
    endif ()
    execute_process (COMMAND make CONFIG_PREFIX=${PATH} install WORKING_DIRECTORY ${PATH_BUSYBOX})
    file (MAKE_DIRECTORY ${PATH}/dev)
    file (MAKE_DIRECTORY ${PATH}/etc)
    file (MAKE_DIRECTORY ${PATH}/home)
    file (MAKE_DIRECTORY ${PATH}/proc)
    file (MAKE_DIRECTORY ${PATH}/sys)
    file (MAKE_DIRECTORY ${PATH}/tmp)
    file (MAKE_DIRECTORY ${PATH}/lib)

    file (REMOVE ${PATH}/init)
    file (REMOVE ${PATH}/startup.sh)
    file (TOUCH  ${PATH}/startup.sh)

    file (APPEND ${PATH}/startup.sh "#!/bin/sh\n")
    file (APPEND ${PATH}/init       "#!/bin/sh\n")

    file (APPEND ${PATH}/init "mount -t proc     proc     /proc\n")
    file (APPEND ${PATH}/init "mount -t sysfs    sysfs    /sys\n")
    file (APPEND ${PATH}/init "mount -t devtmpfs devtmpfs /dev\n")
    file (APPEND ${PATH}/init "mount -t tmpfs    tmpfs    /tmp\n")
    file (APPEND ${PATH}/init "sh /startup.sh\n")
    file (APPEND ${PATH}/init "exec /bin/sh\n")
endfunction()

function  (kernel_image_build NAME)
    string(APPEND PATH "${KLEVER_PATH_IMAGE}/")
    string(APPEND PATH "${NAME}/")
    if    (NOT EXISTS ${PATH})
        message("[Klever] Image ${NAME} not exists.")
        message(SEND_ERROR "Abort")
    endif ()

    if    (NOT EXISTS ${PATH}/image)
        message("[Klever] Image ${NAME} malformed.")
        message(SEND_ERROR "Abort")
    endif ()

    file (REMOVE ${PATH}/build.sh)
    file (APPEND ${PATH}/build.sh "#!/bin/sh\n")
    file (APPEND ${PATH}/build.sh "cd ${PATH}/image\n")
    file (APPEND ${PATH}/build.sh "chmod +x ./startup.sh\n")
    file (APPEND ${PATH}/build.sh "chmod +x ./init\n")

    file (APPEND ${PATH}/build.sh "find . -print0 | cpio --null -ov --format=newc > ../${NAME}.cpio\n")
    file (APPEND ${PATH}/build.sh "gzip ../${NAME}.cpio\n")
    file (APPEND ${PATH}/build.sh "mv   ../${NAME}.cpio.gz ../${NAME}.img\n")

    add_custom_target(${NAME} COMMAND sudo -S /bin/bash ${PATH}/build.sh)
endfunction()