function   (add_kernel_image NAME)
    string (APPEND PATH "${KLEVER_PATH_IMAGE}/")
    string (APPEND PATH "${NAME}/")
    string (APPEND PATH "image")

    file (MAKE_DIRECTORY ${PATH})
    file (MAKE_DIRECTORY ${PATH}/bin)
    file (MAKE_DIRECTORY ${PATH}/dev)
    file (MAKE_DIRECTORY ${PATH}/etc)
    file (MAKE_DIRECTORY ${PATH}/home)
    file (MAKE_DIRECTORY ${PATH}/proc)
    file (MAKE_DIRECTORY ${PATH}/sys)
    file (MAKE_DIRECTORY ${PATH}/usr)
    file (MAKE_DIRECTORY ${PATH}/tmp)
    file (MAKE_DIRECTORY ${PATH}/lib)

    file (REMOVE ${PATH}/init)
    file (REMOVE ${PATH}/startup.sh)
    file (TOUCH  ${PATH}/startup.sh)

    file (APPEND ${PATH}/startup.sh "#!/bin/sh\n")
    file (APPEND ${PATH}/init       "#!/bin/sh\n")

    file (APPEND ${PATH}/init "mount -t proc     proc     /proc\n")
    file (APPEND ${PATH}/init "mount -t sysfs    sysfs    /sys\n")
    file (APPEND ${PATH}/init "mount -t devtmpfs devtmpfs /dev\n")
    file (APPEND ${PATH}/init "mount -t tmpfs    tmpfs    /tmp\n")
    file (APPEND ${PATH}/init "sh /startup.sh\n")
    file (APPEND ${PATH}/init "exec /bin/sh\n")
endfunction()

function  (kernel_image_build NAME)
    string(APPEND PATH "${KLEVER_PATH_IMAGE}/")
    string(APPEND PATH "${NAME}/")
    string(APPEND PATH "image")
    if    (NOT EXISTS ${PATH})
        message("[Klever] Image ${NAME} not exists.")
        message(SEND_ERROR "Abort")
    endif ()

    execute_process(COMMAND sudo -S chown root -R ./      WORKING_DIRECTORY ${PATH})
    execute_process(COMMAND sudo -S chgrp root -R ./      WORKING_DIRECTORY ${PATH})
    execute_process(COMMAND sudo -S chmod +x ./bin/*      WORKING_DIRECTORY ${PATH})
    execute_process(COMMAND sudo -S chmod +x ./init       WORKING_DIRECTORY ${PATH})
    execute_process(COMMAND sudo -S chmod +x ./startup.sh WORKING_DIRECTORY ${PATH})

    string           (APPEND COMMAND "find ./image/ -print0 | cpio --null -ov --format=newc > ${NAME}.cpio && ")
    string           (APPEND COMMAND "gzip ./${NAME}.cpio && ")
    string           (APPEND COMMAND "rm   ./${NAME}.cpio && ")
    string           (APPEND COMMAND "mv   ./${NAME}.cpio.gz ${NAME}.img")
    add_custom_target(${NAME} COMMAND /bin/bash ${COMMAND} WORKING_DIRECTORY ${KLEVER_PATH_IMAGE}/${NAME})
endfunction()