function  (add_kernel NAME MAJOR MINOR)
    string(APPEND PATH ${KLEVER_PATH_KERNEL}/${NAME})
    if    (NOT EXISTS  ${PATH})
        fetch_kernel(${MAJOR} ${MINOR})
        string      (APPEND ARCHIVE_NAME linux-${MAJOR}.${MINOR}.tar.gz)
        string      (APPEND ARCHIVE_PATH ${KLEVER_PATH_KERNEL_ARCHIVE}/)
        string      (APPEND ARCHIVE_PATH ${ARCHIVE_NAME})

        execute_process(COMMAND tar xvzf ${ARCHIVE_PATH} WORKING_DIRECTORY ${KLEVER_PATH_KERNEL})
        if   (NOT EXISTS ${KLEVER_PATH_KERNEL}/linux-${MAJOR}.${MINOR})
            message("[Klever] Failed to extract kernel archive at ${KLEVER_PATH_KERNEL}/linux-${MAJOR}.${MINOR}")
            message(SEND_ERROR "Abort")
        endif()
        file (RENAME ${KLEVER_PATH_KERNEL}/linux-${MAJOR}.${MINOR} ${PATH})
    endif()

    if   (EXISTS ${PATH}/Kbuild.old)
        file (REMOVE    ${PATH}/Kbuild)
        file (COPY_FILE ${PATH}/Kbuild.old ${PATH}/Kbuild)
    else ()
        file (COPY_FILE      ${PATH}/Kbuild ${PATH}/Kbuild.old)
        file (MAKE_DIRECTORY ${PATH}/klever)
    endif()

    if   (NOT EXISTS ${PATH}/.config)
        if   (EXISTS /usr/bin/konsole)
            string (APPEND COMMAND "konsole --workdir ${PATH} --hold -e ")
            string (APPEND COMMAND "make menuconfig -j${KLEVER_JOB}")
        endif()
        execute_process(COMMAND /bin/bash -c ${COMMAND})
    endif()

    unset(ARCHIVE_NAME)
    unset(ARCHIVE_PATH)
    unset(PATH)
endfunction()