function  (kernel_config NAME NAME_KERNEL)
    string(APPEND PATH   "${KLEVER_PATH_KERNEL}/${NAME_KERNEL}")
    string(APPEND CONFIG "${PATH}/.config")
    if    (NOT EXISTS ${PATH})
        message("[Klever] Kernel named ${NAME_KERNEL} not found at ${KLEVER_KERNEL_PATH}")
        message(SEND_ERROR "Abort")
    endif()

    if   (EXISTS /usr/bin/konsole)
        string (APPEND COMMAND "konsole --workdir ${PATH} --hold -e ")
        string (APPEND COMMAND "make menuconfig -j${KLEVER_JOB}")
    endif()
    add_custom_target(${NAME} COMMAND /bin/bash -c ${COMMAND})
endfunction()