function   (add_kernel_feature NAME KERNEL)
    string (APPEND PATH_KERNEL  ${KLEVER_PATH_KERNEL}/${KERNEL})
    string (APPEND PATH_FEATURE ${PATH_KERNEL}/klever/${NAME})
    string (APPEND BUILD        ${PATH_FEATURE}/Kbuild)

    file   (REMOVE ${BUILD})
    file   (APPEND ${BUILD} "obj-y += ${NAME}.o\n\n")
    file   (APPEND ${PATH_KERNEL}/Kbuild "\nobj-y += klever/${NAME}/\n")
    unset  (PATH_KERNEL)
    unset  (PATH_FEATURE)
    unset  (BUILD)
endfunction()

function   (add_kernel_feature_debug NAME KERNEL)
    string (APPEND PATH_KERNEL  ${KLEVER_PATH_KERNEL}/${KERNEL})
    string (APPEND PATH_FEATURE ${PATH_KERNEL}/klever/${NAME})
    string (APPEND BUILD        ${PATH_FEATURE}/Kbuild)

    file   (REMOVE ${BUILD})
    file   (APPEND ${BUILD} "ccflags-y += -g -DDEBUG\n")
    file   (APPEND ${BUILD} "obj-y += ${NAME}.o\n\n")
    file   (APPEND ${PATH_KERNEL}/Kbuild "\nobj-y += klever/${NAME}/\n")
    unset  (PATH_KERNEL)
    unset  (PATH_FEATURE)
    unset  (BUILD)
endfunction()