function  (kernel_package_define NAME)
    string(APPEND BUILD ${KLEVER_PATH_PACKAGE}/${NAME}/Kbuild)
    if    (NOT EXISTS ${BUILD})
        message("[Klever] Feature ${NAME} is malformed")
        message(SEND_ERROR "Abort")
    endif ()

    foreach    (DEF IN LISTS ARGN)
        file   (APPEND ${BUILD} "ccflags-y +=")
        file   (APPEND ${BUILD} "-D${DEF}\n")
    endforeach ()
    file (APPEND ${BUILD} "\n")
    unset(BUILD)
endfunction()