function   (add_kernel_source par_name)
    file                 (RELATIVE_PATH par_path ${CMAKE_SOURCE_DIR} ${CMAKE_CURRENT_SOURCE_DIR})
    add_library          (${par_name} STATIC  ${ARGN})
    set_target_properties(${par_name} PROPERTIES KERNEL_SOURCE "")
    foreach    (SRC IN LISTS ARGN)
        string (FIND ${SRC} ".h" SRC_TYPE REVERSE)
        if   (NOT SRC_TYPE EQUAL -1)
            continue()
        endif()
        string (REPLACE ".c" ".o" SRC ${SRC})
        list   (APPEND SRC_LIST ${SRC})
    endforeach ()
    set_target_properties(${par_name} PROPERTIES KERNEL_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR})
    set_target_properties(${par_name} PROPERTIES KERNEL_SOURCE     "${SRC_LIST}")
endfunction()