function (add_kernel_module NAME)
    string (APPEND PATH  "${KLEVER_PATH_MODULE}/")
    string (APPEND PATH  "${NAME}")
    string (APPEND BUILD "${PATH}/Kbuild")

    file   (REMOVE ${BUILD})
    file   (APPEND ${BUILD} "obj-m += ${NAME}.o\n\n")
    unset  (BUILD)
    unset  (PATH)
endfunction()

function   (kernel_module_build NAME MODULE KERNEL)
    string (APPEND KERNEL "${KLEVER_PATH_KERNEL}/${KERNEL}")
    string (APPEND PATH   "${KLEVER_PATH_MODULE}/")
    string (APPEND PATH   "${MODULE}")
    string (APPEND BUILD  "${PATH}/Kbuild")

    string (APPEND COMMAND "make")
    string (APPEND COMMAND "-j ${KLEVER_JOB} ")
    string (APPEND COMMAND "-C ${KERNEL} ")
    string (APPEND COMMAND "M =${BUILD} ")
    add_custom_target (${NAME}-clean COMMAND /bin/bash ${COMMAND} clean   WORKING_DIRECTORY ${PATH})
    add_custom_target (${NAME}       COMMAND /bin/bash ${COMMAND} modules WORKING_DIRECTORY ${PATH})

    unset  (COMMAND)
    unset  (KERNEL)
    unset  (BUILD)
    unset  (PATH)
endfunction()

function   (kernel_module_build_host NAME MODULE)
    string (APPEND KERNEL "/lib/modules/${CMAKE_HOST_SYSTEM_VERSION}/build")
    string (APPEND PATH   "${KLEVER_PATH_MODULE}/")
    string (APPEND PATH   "${MODULE}")
    string (APPEND BUILD  "${PATH}/Kbuild")

    string (APPEND COMMAND "make")
    string (APPEND COMMAND "-j ${KLEVER_JOB} ")
    string (APPEND COMMAND "-C ${KERNEL} ")
    string (APPEND COMMAND "M =${BUILD} ")
    add_custom_target (${NAME}-clean COMMAND /bin/bash ${COMMAND} clean   WORKING_DIRECTORY ${PATH})
    add_custom_target (${NAME}       COMMAND /bin/bash ${COMMAND} modules WORKING_DIRECTORY ${PATH})

    unset  (COMMAND)
    unset  (KERNEL)
    unset  (BUILD)
    unset  (PATH)
endfunction()