function (add_kernel_module NAME)
    string (APPEND PATH  "${KLEVER_PATH_MODULE}/")
    string (APPEND PATH  "${NAME}")
    string (APPEND BUILD "${PATH}/Kbuild")

    file   (REMOVE ${BUILD})
    file   (APPEND ${BUILD} "obj-m += ${NAME}.o\n\n")
    unset  (BUILD)
    unset  (PATH)

    if    (PRESET_ARCH_X86_64)
        kernel_module_define(${NAME} PRESET_ARCH_X86_64)
        kernel_module_define(${NAME} PRESET_ARCH_BIT=64)
    elseif(PRESET_ARCH_X86)
        kernel_module_define(${NAME} PRESET_ARCH_X86)
        kernel_module_define(${NAME} PRESET_ARCH_BIT=32)
    endif ()
endfunction()

function   (kernel_module_build NAME KERNEL)
    string (APPEND PATH_KERNEL "${KLEVER_PATH_KERNEL}/${KERNEL}")
    string (APPEND PATH        "${KLEVER_PATH_MODULE}/")
    string (APPEND PATH        "${NAME}")

    add_custom_target (${NAME}-build COMMAND sudo -S make -C ${PATH_KERNEL} M=${PATH} modules)
    add_custom_target (${NAME}-clean COMMAND sudo -S make -C ${PATH_KERNEL} M=${PATH} clean)
    unset  (PATH_KERNEL)
    unset  (PATH)
endfunction()

function   (kernel_module_build_host NAME)
    string (APPEND KERNEL "/lib/modules/${CMAKE_HOST_SYSTEM_VERSION}/build")
    string (APPEND PATH   "${KLEVER_PATH_MODULE}/")
    string (APPEND PATH   "${NAME}")

    add_custom_target (${NAME}-build COMMAND sudo -S make -C ${KERNEL} M=${PATH} modules)
    add_custom_target (${NAME}-clean COMMAND sudo -S make -C ${KERNEL} M=${PATH} clean)
    unset  (KERNEL)
    unset  (PATH)
endfunction()