function  (kernel_module_source NAME KERNEL)
    string(APPEND PATH  ${KLEVER_PATH_MODULE}/${NAME})
    string(APPEND BUILD ${PATH}/Kbuild)
    if    (NOT EXISTS ${BUILD})
        message("[Klever] Module ${NAME} is malformed")
        message(SEND_ERROR "Abort")
    endif ()

    foreach    (SOURCE IN LISTS ARGN)
        get_target_property(SOURCE_PATH ${SOURCE} KLEVER_SOURCE_PATH)
        get_target_property(SOURCE_OBJ  ${SOURCE} KLEVER_SOURCE)

        file    (RELATIVE_PATH PATH ${PATH_FEATURE} ${SOURCE_PATH})
        foreach (OBJ ${SOURCE_OBJ})
            file(APPEND ${BUILD} "\t${PATH}/${OBJ}\\\n")
        endforeach ()
        file   (APPEND ${BUILD} "\n\n")
    endforeach ()
endfunction()