function  (kernel_module_source NAME)
    string(APPEND PATH_MODULE ${KLEVER_PATH_MODULE}/${NAME})
    string(APPEND BUILD       ${PATH_MODULE}/Kbuild)
    if    (NOT EXISTS ${BUILD})
        message("[Klever] Module ${NAME} is malformed")
        message(SEND_ERROR "Abort")
    endif ()

    file   (APPEND ${BUILD} "${NAME}-objs += \\\n")
    foreach(SOURCE IN LISTS ARGN)
        get_target_property(SOURCE_PATH ${SOURCE} KLEVER_SOURCE_PATH)
        get_target_property(SOURCE_OBJ  ${SOURCE} KLEVER_SOURCE)

        file    (RELATIVE_PATH PATH ${PATH_MODULE} ${SOURCE_PATH})
        foreach (OBJ ${SOURCE_OBJ})
            file(APPEND ${BUILD} "\t${PATH}/${OBJ}\\\n")
        endforeach ()
    endforeach ()
    file   (APPEND ${BUILD} "\n\n")
endfunction()